### ISSUE TITLE
cannot show the image 

### ISSUE THREAD

**Issue by adustdu2015** [rharter/gl-helpers#1]
when i run the sample module,the app cannot show the image.

**Comment by 357847847** [comment]
private static final String SIMPLE_FRAGMENT = ""
                + "precision mediump float;\n"
                + "varying highp  vec2 texCoord;\n"
                + "uniform sampler2D image;\n"
                + "void main() {\n"
                + "  gl_FragColor = texture2D(image, texCoord);\n"
                + "}";

Add floating-point precision modifier：precision mediump float;

**Comment by adustdu2015** [comment]
Thank you!
